name: Windows 3rd Parties

on:
  workflow_dispatch

jobs:
  windows-3rd-parties:
    runs-on: windows-2019
    steps:
      - name: Install tools
        shell: cmd
        run: choco install wget curl jq --no-progress

      - name: Install OpenModelica
        shell: cmd
        run: |
          cd \
          wget -nv https://github.com/dynawo/dynawo/releases/download/v1.3.1/Dynawo_Windows_v1.3.1.zip
          7z x Dynawo_Windows_v1.3.1.zip dynawo\OpenModelica\ -r -oOpenModelica
          cd OpenModelica\dynawo
          7z a OpenModelica.zip -r OpenModelica\*

      - name: Upload OpenModelica, 3rd parties and dynawo distribution
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         url=$(curl -s https://api.github.com/repos/gautierbureau/dynawo-windows/releases/tags/windows-3rd-parties | jq -r '.assets_url')
         cd /d
         ls
         echo $url
         ls OpenModelica/dynawo/OpenModelica.zip
         curl --retry 20 --retry-delay 0 --retry-max-time 40 --max-time 3600 --limit-rate 200K -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/zip" -X POST ${url}?name=OpenModelica-windows.zip --data-binary @OpenModelica/dynawo/OpenModelica.zip

      # - name: Build Dynawo Third Parties
      #   shell: cmd
      #   run: |
      #     call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      #     cd \dynawo
      #     set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\;C:\vcpkg;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts;C:\hostedtoolcache\windows\Python\3.7.9\x64;C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.352-8\x64\bin;C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\Chocolatey\bin;C:\Program Files\PowerShell\7\;C:\Program Files\OpenSSL\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.6\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\GitHub CLI\;C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;
      #     cmake -Wno-dev -S dynawo/3rdParty -B b-3-p -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../d-3-p -DOPENMODELICA_INSTALL=../OpenModelica -DOPENMODELICA_SRC=../OpenModelica/Source -DOMDEV_HOME=../OMDev -G "NMake Makefiles"
      #     cmake --build b-3-p --target openmodelica
      #     cmake --build b-3-p
      #     cd ..
      #     ren d-3-p dynawo-3rd-parties-windows
      #     7z a dynawo-3rd-parties-windows.zip -r dynawo-3rd-parties-windows\*
      #
      # - name: Move zips
      #   shell: cmd
      #   run: |
      #     mv D:\OpenModelica.zip OpenModelica.zip
      #     mv D:\dynawo-3rd-parties-windows.zip dynawo-3rd-parties-windows.zip
      #
      # - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      #   with:
      #     delete_release: true
      #     tag_name: windows-3rd-parties
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #
      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "windows-3rd-parties"
      #     prerelease: true
      #     title: "Windows 3rd Parties"
      #     files: |
      #       OpenModelica.zip
      #       dynawo-3rd-parties-windows.zip
