name: Windows 3rd Parties

on:
  workflow_dispatch

jobs:
  windows-3rd-parties:
    runs-on: windows-2019
    steps:
      - name: Install tools
        shell: cmd
        run: choco install wget curl jq --no-progress

      - name: Git clone
        shell: cmd
        run: |
          cd \
          git config --global core.autocrlf input & git config --global core.eol lf & git clone https://github.com/dynawo/dynawo.git

      - name: Install OpenModelica
        shell: cmd
        run: |
          cd \
          wget -nv https://github.com/gautierbureau/dynawo-windows/releases/download/test/OpenModelica.zip
          7z x OpenModelica.zip
          dir

      # - name: Build Dynawo Third Parties
      #   shell: cmd
      #   run: |
      #     call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      #     cd \dynawo
      #     cmake -Wno-dev -S dynawo/3rdParty -B b-3-p -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../d-3-p -DOPENMODELICA_INSTALL=../OpenModelica -DOPENMODELICA_SRC=../OpenModelica/Source -DOMDEV_HOME=../OMDev -G "NMake Makefiles"
      #     cmake --build b-3-p --target omdev
      #     cmake --build b-3-p --target openmodelica
      #     cmake --build b-3-p
      #     cd ..
      #     ren d-3-p dynawo-3rd-parties-windows
      #     7z a dynawo-3rd-parties-windows.zip -r dynawo-3rd-parties-windows\*

      - name: Move zips
        shell: cmd
        run: |
          mv D:\OpenModelica.zip OpenModelica.zip
          mv D:\dynawo-3rd-parties-windows.zip dynawo-3rd-parties-windows.zip
          dir

      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: windows-3rd-parties
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "windows-3rd-parties"
          prerelease: true
          title: "Windows 3rd Parties"
          files: |
            OpenModelica.zip
            dynawo-3rd-parties-windows.zip

# \dynawo-3rd-parties-windows.zip
