name: curl

on: push

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      # - name: Install curl
      #   shell: cmd
      #   run: |
      #     choco install curl --no-progress
      #     curl --help

      # - name: Test bash
      #   shell: bash
      #   run: |
      #    url=$(curl -s --request GET https://api.github.com/repos/gautierbureau/dynawo-windows/releases/latest | grep upload_url | cut -d '"' -f 4 | grep -o ".*assets")
      #    echo $url
      #    pwd

      - name: Move git
        shell: cmd
        run: |
          cd
          dir
          cd ..
          dir
          mv dynawo-windows \
          cd \
          dir
          cd
          cd dynawo-windows
          dir
