name: curl

on: push

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Install curl
        shell: cmd
        run: |
          choco install curl jq --no-progress
          curl --help

      # - name: Test bash
      #   shell: bash
      #   run: |
      #    url=$(curl -s --request GET https://api.github.com/repos/gautierbureau/dynawo-windows/releases/latest | grep upload_url | cut -d '"' -f 4 | grep -o ".*assets")
      #    echo $url
      #    pwd
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Move git
        shell: cmd
        run: |
          cd
          dir
          cd ..
          dir
          mv dynawo-windows \
          md dynawo-windows
          cd \
          dir
          cd
          cd dynawo-windows
          dir

      - name: Test
        shell: bash
        run: |
          url=$(curl -s https://api.github.com/repos/dynawo/dynawo/releases/tags/nightly | jq -r '.assets_url')
          echo $url
