name: CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Install curl
        shell: cmd
        run: |
          choco install curl --no-progress
          curl --help
